### ISSUE TITLE
Client access via web GUI - set IP

### ISSUE THREAD

**Issue by jl-678** [FoldingAtHome/fah-client-bastet#102] opened 2023-01-28 15:13 UTC
A core part of the client access process assumes that the user will go to http://app.foldingathome.org.  This works, but it assumes that the FAH Client exists on 127.0.0.1.  This can be changed on typing via CTRL-Shift-L in the browser and entering a new IP.  This is not very intuitive and is not even doable on tablet and mobile browsers.

Suggestion: Can we add some way to configure this behavior?  If not in the client then maybe via app.foldingathome.org? (For example have an option like http://app.foldingathome.org?ip=<ip>&port=<port>?)

I was not sure if I needed to post this issue here or in the client section.  My apologies if this is the wrong place.

**Comment by kbernhagen** [comment] 2023-01-29 00:01
This is a Web Conreol issue.

See also FoldingAtHome/fah-web-client-bastet/issues/61

**Comment by jcoffland** [comment] 2023-01-29 15:56
Duplicate of https://github.com/FoldingAtHome/fah-web-client-bastet/issues/61

**Closed by jcoffland** 2023-01-29 15:56 UTC
