### ISSUE TITLE
v8.4.6 does not halt folding after BAD_WORK_UNIT 

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-client-bastet#305] opened 2024-11-13 06:44 UTC
After client halts folding after BAD_WORK_UNIT, I cannot restart folding on that Group.
I Paused the slot, then tried start folding on it again with different parameters. Group remains halted.
V8.4.6
Windows

**Comment by jcoffland** [comment] 2024-11-13 11:46
Please post the log.

**Comment by muziqaz** [comment] 2024-11-13 11:59
Sorry, Joe, it seems it was remote monitoring delay.
It seems new client is not stopping folding after WU has failed
![Screenshot_2024-11-13-11-54-24-914_org mozilla firefox](https://github.com/user-attachments/assets/045dea95-8a95-44ea-a974-a416c82e4bfe)
![Screenshot_2024-11-13-11-54-53-951_org mozilla firefox](https://github.com/user-attachments/assets/3381795d-86a5-4d3c-a0a1-222efe2e3469)

See attached how many units my pc failed during the night. There is a snippet of the log which shows what type of failure it was.
I will rename the issue topic if I can.

**Comment by jcoffland** [comment] 2024-11-13 12:17
It's doing the correct thing.  The WUs are failing due to ``exception: clKernelArg`` then waiting 17 minutes between retries.  There are apparently two groups so both retry around the same time.  I'm not sure why the call to ``clKernelArg()`` is failing.  This can be caused by a lack of GPU memory or system memory or several other issues.

The maximum delay is currently set to 2^10 sec ~= 17mins.  This could be increased.

**Comment by jcoffland** [comment] 2024-11-13 12:18
Core 0x24 really shouldn't be returning ``BAD_WORK_UNIT`` here because there's probably nothing wrong with the WU.

**Comment by muziqaz** [comment] 2024-11-13 12:22
Timer is fine, but can it completely halt after like 3 failed attempts. Because even with the current timer you can see how many WUs I have wasted.
Now to the original issue, so is it possible that I was attempting to start folding again within that cool down period?
Hm, I'll have to test it thoroughly when I'm at home and not through remote connection, to rule out connection issues

**Comment by muziqaz** [comment] 2024-11-13 12:25
> Core 0x24 really shouldn't be returning `BAD_WORK_UNIT` here because there's probably nothing wrong with the WU.

That's an issue with specific AMD architecture.

**Comment by jcoffland** [comment] 2024-11-13 12:25
Pausing should reset the delays.

**Comment by muziqaz** [comment] 2024-11-13 12:50
> Pausing should reset the delays.

It did not, when I tried it in the morning, remotely.
I will check again I several hours.

**Comment by jcoffland** [comment] 2024-11-13 14:58
Should be fixed in v8.4.7.

**Comment by muziqaz** [comment] 2024-11-13 23:42
![pause](https://github.com/user-attachments/assets/5652ca90-3f7b-4292-abd6-778077314c1b)

We are a go!
Now, one thing: Progress bar is saying NaN%, which is the same when WU just downloaded and had no progress yet.
We need some sort of message instead of NaN%, like Too Many Errors. Or Halted, or Failed. That user can clearly see that it failed.
Because I can see it now, that users will notice paused group, and will go, hm, what is this NaN%, I thought I pressed fold, so they will press fold, and leave it be until they notice it being paused again.

**Closed** 2024-11-20 12:15 UTC
Labels: enhancement
