### ISSUE TITLE
v8 does not always show downloaded and uploaded WU sizes and progress in the log

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-client-bastet#292] opened 2024-09-29 21:38 UTC
Hi,
just noticed, that some of the projects are missing size information at download stage and upload stage in the logs. Is this server side set up issue, or is this v8 bug.
p12422 is showing the sizes (at least a download, I'm yet to finish this WU)
p12462 and p12421 (and many more) are not showing the sizes at download or upload.

**Comment by jcoffland** [comment] 2024-10-01 11:26
Possible duplicate of #130

**Comment by muziqaz** [comment] 2024-10-01 11:45
Indeed it is, should I close this one?

**Closed** 2024-10-01 13:52 UTC
