### ISSUE TITLE
Cloned machines have same F@H ID which leads to conflicts

### ISSUE THREAD

**Issue by hucker75** [FoldingAtHome/fah-client-bastet#216] opened 2024-02-09 16:10 UTC
I have two almost identical machines, I cloned one from the other.  With the old Beta it was ok, but the new Beta thinks they're the same machine.  Where is this info stored?

**Comment by kbernhagen** [comment] 2024-02-09 19:49
The top client.db has the client identity, among other things. You should not copy it when cloning.

When a client is linked to an account, it will pick up user, team, passkey, cause.

**Comment by kbernhagen** [comment] 2024-02-09 19:50
You should not copy the work directory either.

**Comment by kbernhagen** [comment] 2024-02-09 19:52
Cloning is a bad idea in general.

**Comment by hucker75** [comment] 2024-02-09 20:12
In future I'll just uninstall/reinstall Folding after the clone.  That seems to have fixed it this time.

Oddly the previous Beta didn't mind.

**Comment by kbernhagen** [comment] 2024-02-09 20:15
The previous beta did not have accounts.

**Comment by hucker75** [comment] 2024-02-10 05:43
I thought it still would have confused things by asking for a work unit when the server thought it already had one, as it's the same machine.  Or did the server assume I had twice as many CPU cores and GPUs as I did?

One of the two clones is now not showing up on the other machines' list on web control.  Not sure why.  I'll try reinstalling and making sure the items you said above have been deleted.  Even telling the uninstaller to delete "data", it remembered who my account, or was that the browser?

**Comment by kbernhagen** [comment] 2024-02-10 05:50
The browser stores your login. 

I don’t know how the I’d was used previously. Or by servers.

**Comment by hucker75** [comment] 2024-02-10 06:03
I just rebooted both machines, and now they both appear, I don't like intermittent problems.

**Comment by kbernhagen** [comment] 2024-02-10 06:54
Agreed.

There has been a problem with clients disconnecting from the node.
It seems to mostly be on Windows around zero hours UTC.
The cause has not been tracked down yet.
A client restart is sufficient to reconnect.

**Comment by hucker75** [comment] 2024-02-10 07:25
So it's just coincidence it was one of the cloned machines?  I have 6 other machines which aren't cloned, and they haven't disconnected.

I did try restarting both Folding clients, this didn't fix it, I had to restart Windows.

**Comment by kbernhagen** [comment] 2024-02-10 07:31
Interesting. Joseph might know if it's more than coincidence.

**Comment by hucker75** [comment] 2024-02-11 09:18
And last night two different machines did it.  Looks like it's nothing to do with the type of machine.

To get them back on, logging out and in on the machine which had disappeared didn't help, I had to exit and relaunch folding.

**Comment by hucker75** [comment] 2024-02-11 12:56
> Cloning is a bad idea in general.

It's a common thing for those of us with many machines.  Folding should be able to spot there are two identical machines, and get them to regenerate an ID.

**Comment by kbernhagen** [comment] 2024-02-11 21:19
> > Cloning is a bad idea in general.
> 
> It's a common thing for those of us with many machines. Folding should be able to spot there are two identical machines, and get them to regenerate an ID.

I was speaking of just cloning the fah data directory.

For a client to know it has a duplicate id, it would probably need to also use some hardware id. I don't think @jcoffland wants to do that.

Some people have the data directory on a flash drive, and use it on different machines, one at a time. Any duplicate detection scheme would have to account for that. Ideas are welcome.

**Comment by hucker75** [comment] 2024-02-11 21:38
I think the detection should come from the server when two machines connect at once claiming to be the same one.

**Comment by kbernhagen** [comment] 2024-02-11 21:44
Ah, so just a collision detection? Ask duplicate clients to regenerate their id?

**Comment by kbernhagen** [comment] 2024-02-11 21:50
Looks like the client id is sent when requesting work.
I don't know if the work upload client id needs to match.

**Comment by hucker75** [comment] 2024-02-11 22:12
Yes, collision detection.  The current alternative of uninstalling and reinstalling destroys the current job anyway.

**Comment by kbernhagen** [comment] 2024-02-11 22:21
Collision detection of machine name might also be useful.

**Comment by jcoffland** [comment] 2024-02-12 10:28
A client's F@H ID is computed from it's RSA key pair.  Specifically from it's public key.  If you copy the client DB then it will have the same ID and appear to be the same machine on the F@H network.

This could be a problem for others since cloning VMs or Docker instances is quite common.  One solution is to make sure to delete ``/var/lib/fah-client/client.db`` before cloning a F@H instance.  Another possibility would be for the client to try to detect the machine ID and regenerate its ID if it detects a change in the ID of the machine it's on.

The difficulty with the later solution is that Linux, Windows and macOS will all have different methods for acquiring a unique machine ID.

# Linux
We could use ``/etc/machine-id``.  However, if you clone a Linux machine you could also copy this file but then maybe it's the user's fault.

# Windows
Maybe ``HKLM\SOFTWARE\Microsoft\Cryptography\MachineGuid``.

# macOS
Maybe ``ioreg -ad2 -c IOPlatformExpertDevice | plutil -extract IORegistryEntryChildren.0.IOPlatformUUID raw -``

**Comment by hucker75** [comment] 2024-02-12 18:22
I assume cloning software knows this and removes the file?

**Comment by marcosfrm** [comment] 2024-02-12 18:37
> I assume cloning software knows this and removes the file?

I have no idea.

Running once the cloned system booted will probably work too:

```
sudo truncate -s 0 /etc/machine-id
sudo reboot
```
(I recommend truncating rather than removing it to preserve extended attributes like SELinux context)

**Comment by hucker75** [comment] 2024-02-12 20:25
Sudo :-)  Don't we all log in as root?  Makes things so much easier.

**Comment by hucker75** [comment] 2024-02-13 00:03
> Agreed.
> 
> There has been a problem with clients disconnecting from the node. It seems to mostly be on Windows around zero hours UTC. The cause has not been tracked down yet. A client restart is sufficient to reconnect.

Just saw it happen at midnight UTC.  Everything disconnected, then all but one reconnected.  Some kinda reset is going on.

**Comment by jackschmidt** [comment] 2024-02-16 01:29
I think the new 8.3.6 code might have a surprise effect that causes a work unit to be lost/dumped

I'm assuming that turning in a work unit requires having access to the private key used to request it.

If someone uses 8.3.6, gets a new work unit, and then uses that same client.db on another 8.3.6, then the old RSA key used to turn in the work unit will be deleted.

For example, while working around the SHA1 bug a while back, I switched from running directly on RHEL (yucky) to podman running ubuntu (buggy due to the sha1 issue) to podman running arch (perfect). It was the same VM the whole time, and no work units were lost. However, /etc/machine-id changed.

With 8.3.6, running that way will cause the client to delete the old key and lose the work unit.

would it make sense to keep a mapping of machine-id -> RSA key?

Changing the name from 'key' to the concatenation 'key' + machine_id might work well.

**Comment by jcoffland** [comment] 2024-02-16 15:10
> I think the new 8.3.6 code might have a surprise effect that causes a work unit to be lost/dumped
>
> I'm assuming that turning in a work unit requires having access to the private key used to request it.
>
> If someone uses 8.3.6, gets a new work unit, and then uses that same client.db on another 8.3.6, then the old RSA key used to turn in the work unit will be deleted.

If you cause the client to change keys then it will have a different ID and will not be able to continue any preexisting WUs.  This is intentional.  Say for example, you copy a fah-client install to a new machine.  The client will detect that it's on a new machine and generate a new key.  Then it will discard any WUs that were from the old client ID.  The original copy can continue to run as normal.

I suppose the downside is that if you want to move a client to a new machine and finish it's WUs on the new machine but this is just not a scenario we support.  If you really wanted to do it you could modify the ``machine-id`` in the ``client.db`` to match the new machine.  This would prevent the client from generating a new key.

**Comment by jcoffland** [comment] 2024-05-25 11:09
Should be fixed at least as of v8.3.16.

**Closed by jcoffland** 2024-05-25 11:09 UTC
Labels: bug
