### ISSUE TITLE
Allow time- and/or temp-based scheduling of resource usage settings 

### ISSUE THREAD

**Issue by osirisOfGit** [FoldingAtHome/fah-client-bastet#268] opened 2024-08-11 15:59 UTC
I have a decently powerful rig, but live in an area that is regularly 90F+ for a solid portion of the year and unabatedly sunny, and don't have a great setup for managing thermals - to save costs on A/C, I increase the temp threshold while i'm at work, but that also means my rig suffers from pretty severe heat overload during the day. Out of concern for my rig's longevity, i have to halve FAH's resource utilization while i'm at work, but during the late afternoons/nights, i can crank it up to full as i have the A/C running and the lack of sun makes managing indoor temp far easier.

Unfortunately, since I often forget to go in and change the resource utilization when i get home, or am not home/on my computer at all, i'm almost always just using 50% of my rig's power, when i would otherwise be fine using 100%.

If there could be a feature implemented to allow me to schedule my resource utilization so it wasn't dependent on my remembering/being around to adjust the sliders, that would allow me to comfortably contribute as much as possible without severely reducing the lifetime of my components (to my understanding anyway, my hardware knowledge is pretty lacking - please correct me if this request is based on any false assumptions!)

**Comment by osirisOfGit** [comment] 2024-08-11 16:10
Alternatively, as part of https://github.com/FoldingAtHome/fah-client-bastet/issues/265, if temperature-based resource utilization is possible, that would be even better

- https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceQueries.html#group__nvmlDeviceQueries_1g92d1c5182a14dd4be7090e3c1480b121
- https://rocm.docs.amd.com/projects/amdsmi/en/latest/doxygen/docBin/html/structamdsmi__dimm__thermal__t.html#a2a7426820d9b0f95f2cfeb3d8a802fed

**Comment by osirisOfGit** [comment] 2024-08-11 16:26
Closely related/possible duplicate of https://github.com/FoldingAtHome/fah-web-client-bastet/issues/53 - not sure how y'all wanna structure the issues between the front-end and back-end

**Comment by jcoffland** [comment] 2024-08-12 11:44
This is a duplicate of FoldingAtHome/fah-web-client-bastet#53 and #11.

**Closed by jcoffland** 2024-08-12 11:44 UTC
Labels: duplicate
