### ISSUE TITLE
Windows 10 and 11 version "forgets" CPU WU after system restart

### ISSUE THREAD

**Issue by muziqaz** [FoldingAtHome/fah-client-bastet#290] opened 2024-09-23 15:14 UTC
I thought it would be better to create a separate issue regarding the WU stuff.
So every time I restart my Windows PCs, both systems FAH client downloads new WU instead of continuing with the old one, which was downloaded and being folded before the restart. On one system I can see 5 WU folders in `Work` directory, while I am only folding one at the moment.
Log is not showing anything suspicious, except some subprocess error `14:20:09:E :Subprocess deallocated while process is still running`
Here is the log.
[log.txt](https://github.com/user-attachments/files/17099920/log.txt)

There has been no alterations to both systems in regards to boot/restart sequence. Everything is default as father Microsoft intended.

Linux system seems to work as intended

I mentioned this issue before in this comment and thread: https://github.com/FoldingAtHome/fah-client-bastet/issues/286#issuecomment-2368484970

**Comment by kbernhagen** [comment] 2024-09-23 19:52
Does the forgetting not happen if you quit the client via sys tray before restarting the system?

**Comment by muziqaz** [comment] 2024-09-23 20:10
> Does the forgetting not happen if you quit the client via sys tray before restarting the system?

Quitting and then restarting resumes from where it stopped.

**Comment by kbernhagen** [comment] 2024-09-23 20:54
My thought, which has been disputed in the past, is that Windows unceremoniously kills the client when there is a reboot, leaving database locked with unsaved changes.

The client is also running a native Win event loop.
Maybe it just needs to catch appropriate messages for logout/shutdown.

**Comment by muziqaz** [comment] 2024-09-23 23:53
Also, what is weird, that V8 is downloading new WU, instead of resetting currently running one to zero.
V7 sometimes used to lose WU's progress if system crash was severe. It had never lost a WU.
Well there were several very rare occasions when another WU would get downloaded while old one was still there, but it would be visible in fahcontrol, and once newly downloaded WU was completed fahclient would pick up the old one and continue from where it left off.
It would be great that I could still complete those other 4 WUs sitting on my SSD with v8

**Comment by jcoffland** [comment] 2024-09-25 12:03
The permissions problem could be caused by either the client trying to start in the wrong directory, the file permissions on ``log.txt`` or it's directory are actually being changed or the client is starting under the wrong user.

**Comment by muziqaz** [comment] 2024-09-25 12:14
I will be able to test this in an hour or so. The test PC has ProgramData/FahClient security settings tweaked to allow writing by any Users, which solved the restart issue. Do you have some sort of longer WU for me to download during the test that I do not lose real work? 2 minute long WU would be sufficient. If you don't mind creating something, ping me details in the Slack
Thanks

**Comment by jcoffland** [comment] 2024-09-25 14:12
It does look like the client was hard killed during shutdown.  The log just ends abruptly.  Then when it starts again it says: ``Loaded 0 wus.``

**Comment by muziqaz** [comment] 2024-09-25 14:14
Not sure if that makes any difference, on my Windows 10 PC, FAHClient process is running under muziqaz2 user name.
`ProgramData\FAHClient` security properties list:
CREATOR OWNER (which has no permissions and I am not allowed to change it, it reverts to nothing, when I apply the changes)
SYSTEM (which has full control)
Administrators (MUZIQAZ2\Administrators) (has full control)
Users (MUZIQAZ2\Users) (which has Read & Execute, List contents, Read, Write)

`ProgramData\FAHClient\work` security properties have the same as above

`ProgramData\FAHClient\work\wudirectory` (which got forgotten) security properties have as above, PLUS:
muziqaz2 (MUZIQAZ2\muziqaz2) (which has nothing but Special Permissions ticked)

**Comment by muziqaz** [comment] 2024-09-25 14:18
Just for giggles, I gave full control to muziqaz2 for the WU folder, rebooted, it still downloaded new WU. So doubt this is permission issue

**Comment by jcoffland** [comment] 2024-09-25 14:23
Does this build work any better?: https://master.foldingathome.org/builds/fah-client/windows-10-64bit/release/v8.4.6-b135/fah-client_8.4.6_AMD64.exe

I added detection of the Windows shutdown message.

**Comment by muziqaz** [comment] 2024-09-25 14:26
> It does look like the client was hard killed during shutdown. The log just ends abruptly. Then when it starts again it says: `Loaded 0 wus.`

I don't believe I am breeding killer OSs :D 
If it makes any difference they are Win 11 Pro and Win 10 Pro. Both have 22H2 updates, which seem to be the latest for those OS builds. I believe 22H2 is just a name, and it contains all the latest stuff from 24H2

**Comment by muziqaz** [comment] 2024-09-25 14:32
New version ignored old WU and downloaded new WU after installation even without the system restart :( Is it possible windows process termination method is broken on my systems, which can't be, since it would be hell of the coincidence to have 2 different Windows version sledgehammering processes instead of closing them 
Restarting the system now

**Comment by muziqaz** [comment] 2024-09-25 14:39
Restarting still downloaded new WU
[log.txt](https://github.com/user-attachments/files/17132830/log.txt)

Also, installation did not change `ProgramData\FAHClient` permissions

**Comment by kbernhagen** [comment] 2024-09-25 17:56
Is the Windows logout message also handled by the new code?

**Comment by jcoffland** [comment] 2024-09-25 21:53
I added code to shut the client down if it receives a ``WM_QUERYENDSESSION`` or ``WM_ENDSESSION`` message.

**Comment by bollix47** [comment] 2024-10-16 20:56
Today I had reson to pause folding on W11 and lost all progress using 8.4.5
https://foldingathome.slack.com/archives/C01257G67MW/p1729111718571409

**Comment by jcoffland** [comment] 2024-11-12 14:34
I think this is caused by the same permissions issue as #286.

**Comment by jcoffland** [comment] 2024-11-12 19:15
Is this fixed with v8.4.6?

**Comment by muziqaz** [comment] 2024-11-12 20:42
Still forgetting everything :(

**Comment by muziqaz** [comment] 2024-11-12 20:45
> I think this is caused by the same permissions issue as #286.

Unfortunately, no. Permission issue has now been fixed, but it still forgets everything, while upon restart premissions hold. So definetly not permission issue

**Comment by jcoffland** [comment] 2024-11-13 14:15
I've tried both pausing/unpausing and rebooting with out pausing on my Windows 10 VM and the WU is not lost.

**Comment by muziqaz** [comment] 2024-11-13 14:26
Pause unpause is fine, but reboot is downloading new WUs every time. GPU and CPU groups

**Comment by jcoffland** [comment] 2024-11-13 14:58
Possibly fixed in v8.4.7.

**Comment by muziqaz** [comment] 2024-11-13 19:32
Updating Fahclient while folding a WU forgets that WU after installation and downloads a new one. Then rebooting the system forgets that new one, too and starts downloading another one :(

**Comment by muziqaz** [comment] 2024-11-13 19:36
However, WU which was forgotten upon restart has been saved in History as 8.7% complete. 
WU which was forgotten during installation has not been saved.
All forgotten WUs are still in my Works folder though. Maybe it would be simpler to write some sort of routine to first check works folder locally, and continue whatever is still there?

**Comment by jcoffland** [comment] 2024-11-14 13:58
The problem is that Windows is killing the client before it can save the WU progress.  The client was depending on a clean shutdown to save all WU data.  I added an early save in v8.4.7 so that the WU was not completely lost if the client is killed.  However, the client is still going to loose some data as long as Windows is killing the process.

**Comment by muziqaz** [comment] 2024-11-14 14:08
But v8.4.7 does not resume the work, it still downloads new WU. Old WU is still sitting in the works folder, but web UI does not show it in the main page.

Now, why is update process forgetting WU I was folding? Is Windows process shut down method so brutal?
I remember from time to time Valve Steam would prevent windows restarting until me, the user manually clicked Close the Program upon restart.
I wonder what kind of privileges was Steam working with that it would halt, or delay manual Windows restart?

**Comment by jcoffland** [comment] 2024-11-14 14:34
Yes, the shutdown is brutal.  Process is simply killed.

I'm working on adding code to block the Windows shutdown until F@H can shutdown gracefully.

**Comment by jcoffland** [comment] 2024-11-20 12:16
This should be fixed in v8.4.8.

**Closed by jcoffland** 2024-11-20 12:16 UTC
Labels: bug

**Comment by muziqaz** [comment] 2024-11-20 12:51
Unfortunatelly, still forgetting the WU :( It does all the right things, delays windows restart by showing the message about "FAH is preventing restart, restart anyway", but this message is very brief, and PC restarts on its own before I can click "Restart Anyway" myself. On a bright side, FAH update no longer forgets the currently folded WU, even when I do not pause the WU (TPF goes nuclear after that, but that's another issue).
I have a video of the remotely monitored PC which has been restarted.
In the beginning of the clip at the bottom, you can see one WU being worked on. Then there is a lengthy restart, and at the end of the clip, after restart is complete, PC starts a new, different, WU. This is Windows 10.
https://www.youtube.com/watch?v=Nvsq73fx9cU

**Comment by jcoffland** [comment] 2024-11-20 13:06
It's ok if the message goes away.  It could mean that F@H shutdown correctly.  What does the end of log file look like?

**Comment by jcoffland** [comment] 2024-11-20 13:29
In ``After restart log-20241120-123053.txt`` the core crashes.  Which not great but it's a core 0xa8 bug.

**Comment by muziqaz** [comment] 2024-11-20 13:31
I downloaded that WU while being on v8.4.7, I updated to v8.4.8 at 18%, which retained the WU and progress. Then restart happened (several minutes after the update) and WU/Fahcore crashed. Crash is a bit better, because researcher gets the indication that it crashed, so WU can be reassigned to another person straight away (I believe), instead of being forgotten by fahclient and waiting for expiration.

**Comment by jcoffland** [comment] 2024-11-20 13:34
Maybe there's a missing log in between.  I don't see v8.4.8 before the reboot.

**Comment by jcoffland** [comment] 2024-11-20 13:41
Looking again at the Windows installer code, unfortunately it hard kills the client instead of first requesting a graceful shutdown.

I'm guessing this is what you did:

  1. Install v8.4.8, this killed v8.4.7
  2. Opted not to restart the client after the upgrade
  3. Rebooted
  4. v8.4.8 started and dumped the WU
 
The next thing we need is graceful client shutdown in the installer.  Then it shouldn't lose WUs.

**Comment by muziqaz** [comment] 2024-11-20 13:54
> Maybe there's a missing log in between. I don't see v8.4.8 before the reboot.

That's all what it was around that time stamp. I did not delete anything between receiving the WU in v8.4.7 and it crashing while on v8.4.8

**Comment by muziqaz** [comment] 2024-11-20 13:55
> Looking again at the Windows installer code, unfortunately it hard kills the client instead of first requesting a graceful shutdown.
> 
> I'm guessing this is what you did:
> 
>     1. Install v8.4.8, this killed v8.4.7
> 
>     2. Opted not to restart the client after the upgrade
> 
>     3. Rebooted
> 
>     4. v8.4.8 started and dumped the WU
> 
> 
> The next thing we need is graceful client shutdown in the installer. Then it shouldn't lose WUs.

When client is being updated, installer kills the old fahclient services, no? Because systray goes away.
Then at the last step of the installer I kept the box ticked, and when I clicked finish, it started v8.4.8 straight away

**Comment by jcoffland** [comment] 2024-11-20 15:09
I've implemented a graceful shutdown in the v8.4.9 installer.

**Comment by muziqaz** [comment] 2024-11-20 23:16
OK, Windows shutdown procedure is killing the WU. WU gets dumped before system shutdown. Video:
https://www.youtube.com/watch?v=S_QvHSiBNdc
Logs:
[before update.txt](https://github.com/user-attachments/files/17837749/before.update.txt)

[after update.txt](https://github.com/user-attachments/files/17837750/after.update.txt)

[after system restart.txt](https://github.com/user-attachments/files/17837752/after.system.restart.txt)

I will try restarting with paused WU in a second

**Comment by muziqaz** [comment] 2024-11-20 23:23
Paused WU survived the restart

**Comment by jcoffland** [comment] 2024-11-21 13:39
I think the problem now is that although ``fah-client`` is getting a chance to shutdown gracefully, Windows is still killing the core processes.  Thus the dumping.  I'm looking into if there is a way to ask Windows not to kill the cores from the client because modifying all the cores is not a viable options at least in the near term.

**Comment by muziqaz** [comment] 2024-11-21 13:45
Would the pausing of WU be quicker before fahclient is killed by OS shutdown? Though that might be inconsistent depending on the size of the WUs

**Comment by jcoffland** [comment] 2024-11-21 13:54
``fah-client`` is no longer being killed on shutdown.  It is shutting down gracefully.  The installer is also now shutting the client and thus the cores down gracefully.  Windows may still be killing the cores on shutdown but I'm not sure about this.

From you logs I'm seeing a 0xa8 core bug.  When Windows shutdown the client AND core shutdown gracefully.  However, when the core started back up it crashed.  This, I believe, is a separate issue of the core misbehaving.  You might test this again with a GPU core.

**Comment by jcoffland** [comment] 2024-11-21 14:37
Yes, but that was when the installer was killing the client.

**Comment by muziqaz** [comment] 2024-11-21 14:56
> Yes, but that was when the installer was killing the client.

I thought v8.4.9 installer gracefully closes the client upon update

**Comment by jcoffland** [comment] 2024-11-21 15:17
Sorry, I got my wires crossed.  It is 0x23 core that seems to have the bug since it's the one that crash after restarting from a gracefully shutdown.  I'm guessing 0xa8 restarts cleanly now.

**Comment by muziqaz** [comment] 2024-11-21 15:56
> Sorry, I got my wires crossed. It is 0x23 core that seems to have the bug since it's the one that crash after restarting from a gracefully shutdown. I'm guessing 0xa8 restarts cleanly now.

Unfortunately, a8 is crashing the same way :(
[before reboot.txt](https://github.com/user-attachments/files/17848574/before.reboot.txt)

[after reboot.txt](https://github.com/user-attachments/files/17848575/after.reboot.txt)

**Comment by jcoffland** [comment] 2024-11-21 18:22
That looks like the core was killed by the OS.

**Comment by jcoffland** [comment] 2024-11-21 18:26
In both cases the cores (0xa8 and 0x23) exit with 1073807364 or in hex 0x40010004.  This is caused by the OS killing the process on shutdown.  See this post: https://stackoverflow.com/questions/37078953/in-which-cases-does-program-exit-with-0x40010004-code

I've got some changes for v8.4.10 that might solve this.

**Comment by jcoffland** [comment] 2024-11-21 18:27
In other words, I no longer believe these to be caused by core bugs.  Which is a good thing.
